<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtSession\Module'                                           => __DIR__ . '/Module.php',
  'HtSession\Exception\ExceptionInterface'                     => __DIR__ . '/src/Exception/ExceptionInterface.php',
  'HtSession\Exception\InvalidArgumentException'               => __DIR__ . '/src/Exception/InvalidArgumentException.php',
  'HtSession\Factory\DoctrineDbalSessionSetSaveHandlerFactory' => __DIR__ . '/src/Factory/DoctrineDbalSessionSetSaveHandlerFactory.php',
  'HtSession\Factory\ModuleOptionsFactory'                     => __DIR__ . '/src/Factory/ModuleOptionsFactory.php',
  'HtSession\Factory\SessionManagerFactory'                    => __DIR__ . '/src/Factory/SessionManagerFactory.php',
  'HtSession\Factory\SessionSetSaveHandlerFactory'             => __DIR__ . '/src/Factory/SessionSetSaveHandlerFactory.php',
  'HtSession\Factory\ValidatorPluginManagerFactory'            => __DIR__ . '/src/Factory/ValidatorPluginManagerFactory.php',
  'HtSession\Options\ModuleOptions'                            => __DIR__ . '/src/Options/ModuleOptions.php',
  'HtSession\Options\SessionOptionsInterface'                  => __DIR__ . '/src/Options/SessionOptionsInterface.php',
  'HtSession\Service\SessionManagerProvider'                   => __DIR__ . '/src/Service/SessionManagerProvider.php',
  'HtSession\Service\ValidatorPluginManager'                   => __DIR__ . '/src/Service/ValidatorPluginManager.php',
  'HtSession\Session\BootstrapSession'                         => __DIR__ . '/src/Session/BootstrapSession.php',
  'HtSession\Session\SaveHandler\DoctrineDbal'                 => __DIR__ . '/src/Session/SaveHandler/DoctrineDbal.php',
  'HtSession\Session\SaveHandler\DoctrineDbalOptions'          => __DIR__ . '/src/Session/SaveHandler/DoctrineDbalOptions.php',
);
