<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtSession\Module'                                => __DIR__ . '/Module.php',
  'HtSession\Factory\AccesibilityGuardFactory'      => __DIR__ . '/src/HtSession/Factory/AccesibilityGuardFactory.php',
  'HtSession\Factory\AccessibilityOptionsFactory'   => __DIR__ . '/src/HtSession/Factory/AccessibilityOptionsFactory.php',
  'HtSession\Factory\ModuleOptionsFactory'          => __DIR__ . '/src/HtSession/Factory/ModuleOptionsFactory.php',
  'HtSession\Factory\SessionManagerFactory'         => __DIR__ . '/src/HtSession/Factory/SessionManagerFactory.php',
  'HtSession\Factory\SessionSetSaveHandlerFactory'  => __DIR__ . '/src/HtSession/Factory/SessionSetSaveHandlerFactory.php',
  'HtSession\Options\AccessibilityOptions'          => __DIR__ . '/src/HtSession/Options/AccessibilityOptions.php',
  'HtSession\Options\AccessibilityOptionsInterface' => __DIR__ . '/src/HtSession/Options/AccessibilityOptionsInterface.php',
  'HtSession\Options\ModuleOptions'                 => __DIR__ . '/src/HtSession/Options/ModuleOptions.php',
  'HtSession\Options\SessionOptionsInterface'       => __DIR__ . '/src/HtSession/Options/SessionOptionsInterface.php',
  'HtSession\Service\AccesibilityGuard'             => __DIR__ . '/src/HtSession/Service/AccesibilityGuard.php',
  'HtSession\Service\SessionManagerProvider'        => __DIR__ . '/src/HtSession/Service/SessionManagerProvider.php',
  'HtSession\Session\BootstrapSession'              => __DIR__ . '/src/HtSession/Session/BootstrapSession.php',
);
