<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtSession\Module'                                              => __DIR__ . '/Module.php',
  'HtSession\Exception\InvalidArgumentException'                  => __DIR__ . '/src/HtSession/Exception/InvalidArgumentException.php',
  'HtSession\Factory\DoctrineDbalSessionSetSaveHandlerFactory'    => __DIR__ . '/src/HtSession/Factory/DoctrineDbalSessionSetSaveHandlerFactory.php',
  'HtSession\Factory\ModuleOptionsFactory'                        => __DIR__ . '/src/HtSession/Factory/ModuleOptionsFactory.php',
  'HtSession\Factory\SessionManagerFactory'                       => __DIR__ . '/src/HtSession/Factory/SessionManagerFactory.php',
  'HtSession\Factory\SessionSetSaveHandlerFactory'                => __DIR__ . '/src/HtSession/Factory/SessionSetSaveHandlerFactory.php',
  'HtSession\Factory\ValidatorPluginManagerFactory'               => __DIR__ . '/src/HtSession/Factory/ValidatorPluginManagerFactory.php',
  'HtSession\Options\ModuleOptions'                               => __DIR__ . '/src/HtSession/Options/ModuleOptions.php',
  'HtSession\Options\SessionOptionsInterface'                     => __DIR__ . '/src/HtSession/Options/SessionOptionsInterface.php',
  'HtSession\Service\SessionManagerProvider'                      => __DIR__ . '/src/HtSession/Service/SessionManagerProvider.php',
  'HtSession\Service\ValidatorPluginManager'                      => __DIR__ . '/src/HtSession/Service/ValidatorPluginManager.php',
  'HtSession\Session\BootstrapSession'                            => __DIR__ . '/src/HtSession/Session/BootstrapSession.php',
  'HtSession\Session\SaveHandler\DoctrineDbalTableGateway'        => __DIR__ . '/src/HtSession/Session/SaveHandler/DoctrineDbalTableGateway.php',
  'HtSession\Session\SaveHandler\DoctrineDbalTableGatewayOptions' => __DIR__ . '/src/HtSession/Session/SaveHandler/DoctrineDbalTableGatewayOptions.php',
);
